# Generated by Django 3.2.3 on 2021-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tickets_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='patient',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
