# Generated by Django 3.2.3 on 2021-05-30 14:20

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tickets_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='patient',
            field=api.models.HideCharField(max_length=500),
        ),
    ]
