# Generated by Django 3.2.3 on 2021-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210530_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
