# Generated by Django 3.2.3 on 2021-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210530_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='type',
            field=models.CharField(choices=[('Consultation_medecine_general', 'Consultation Médecine Générale'), ('Consultation_gyneco', 'Consultation Gynéco'), ('Consultation_pediatrique', 'Consultation Pédiatrique'), ('Consultation_sage_femme', 'Consultation Sage Femme'), ('Consultation_rhumatologie', 'Consultation Rhumatologie'), ('Consultation_cardiologie', 'Consultation Cardiologie'), ('Consultation_orl', 'Consultation ORL'), ('Consultation_orphtalologie', 'Consultation Ophtalmologie'), ('Hospitalisation_categorie_1', 'Hospitalisation Catégorie 1'), ('Hospitalisation_categorie_2', 'Hospitalisation Catégorie 2'), ('Hospitalisation_categorie_3', 'Hospitalisation Catégorie 3')], default='Consultation_medecine_general', max_length=100),
        ),
    ]
