# Generated by Django 3.2.3 on 2021-05-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tickets_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
