# Generated by Django 3.2.3 on 2021-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_ticket',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True, verbose_name='Refrence Ticket'),
        ),
    ]
