# Generated by Django 3.2.3 on 2021-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_id_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_ticket',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='Refrence Ticket'),
        ),
    ]
