# Generated by Django 3.2.3 on 2021-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210531_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_ticket',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Refrence Ticket'),
        ),
    ]
