# Generated by Django 3.2.3 on 2021-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210531_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_ticket',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Refrence Ticket'),
        ),
    ]
