# Generated by Django 3.2.3 on 2021-05-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ticket_id_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='montant',
            field=models.IntegerField(editable=False),
        ),
    ]
