# Generated by Django 3.2.3 on 2021-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ticket_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Id Customer')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
