# Generated by Django 3.2.3 on 2021-06-02 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210602_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
